### ISSUE TITLE
Error info: Encountered unrecoverable error in ExportToSpreadsheet duing start up

### ISSUE THREAD

**Issue by eveliuyi** [taltechmicrofluidics/CP-for-droplet-analysis#3]
Hi there, 

When I tried to use this pipeline to analyze my fluorescenct droplet image (grayscale, in Tif format), it gave this error: "**Encountered unrecoverable error in ExportToSpreadsheet duing start up: index 0 is out of bounds for axis 0 with size 0**". But when I tried it with the sample pictures included, the pipeline was working fine. May I ask how should I solve this?

Btw, I am using CellProfiler 4.1.3.

Many thanks!

**Comment by im-sanka** [comment]
Hi @eveliuyi, I am not sure why you encounter such problem. Maybe you can attach a sample from your images here? I will try to check what makes the error. Or, maybe you can delete the "ExportToSpreadsheet" module and replace with the new one from this recent CP?

**Comment by eveliuyi** [comment]
Hi, thanks for your reply! I tried deleting the "ExportToSpreadsheet" module and adding a new one manually, but the problem persisted. 

I have attached the fluorescence images I used here, and their bright field correspondent ones.
[Test Images.zip](https://github.com/taltechmicrofluidics/CP-for-droplet-analysis/files/6415994/Test.Images.zip)

**Comment by im-sanka** [comment]
Hi @eveliuyi I think I just figured your error. So, basically you use our settings for Metadata, NamesAndTypes, and Groups modules. I suggest you change these into the one suits your naming set and define your parameter as well. If you want to bluntly use our pipeline, you need to adjust your naming system for your images. I also checked the the size of your droplets and seems around 40-80 in diameter pixel. So, maybe change this as well. Try to play around with the Thresholding strategy as well to optimize the detection. Otherwise, good luck!

For complete instruction, you can find our guideline in the publication here (page 5 onwards): 
http://www.rsc.org/suppdata/d0/ay/d0ay00031k/d0ay00031k1.pdf

**Comment by eveliuyi** [comment]
Hi @im-sanka  I can analyze my images now after modifying the Metadata, NamesAndTypes, and Groups modules, and the size and threshold in IdentifyingPrimaryObjects module. The results look pretty nice. Thanks for your help!
